In [1]:
%pip install gensim

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [3]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

vec_king = wv['king']

In [4]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [5]:
import pandas as pd
messages=pd.read_csv('SpamClassifier-master/smsspacmcollection/SMSSpamCollection.txt', sep='\t', names=["label", "message"])

In [6]:
messages.shape

(5572, 2)

In [ ]:
X_new.shape

(5557, 100)

In [7]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [8]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\KIIT0001\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [9]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    
    review = [lemmatizer.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [10]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus, messages['message']) if i<1]

[[0, '', '645'], [0, '', ':) '], [0, '', ':-) :-)']]

In [11]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [12]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [13]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))


In [14]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [15]:
import gensim

In [16]:
## Lets train Word2vec from scratch
model=gensim.models.Word2Vec(words)

In [17]:
## To Get All the Vocabulary
model.wv.index_to_key

['to',
 'you',
 'the',
 'it',
 'and',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'will',
 'if',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'home',
 'she',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'hi',
 'phone',
 'they',
 'new',
 'please',
 'later',
 'pls',
 'any',
 'her',
 'ha',
 'co',
 'did',
 'been',
 'msg',
 'min',
 'some',
 'an',
 'night',
 'make',
 'dear',
 'who',
 'here',
 'message',
 'say',
 'well',
 'where',
 're',
 'thing',
 'much',
 'oh',

In [18]:
model.corpus_count

5569

In [19]:
model.epochs

5

In [20]:
model.wv.similar_by_word('good')

[('all', 0.9986921548843384),
 ('night', 0.9986819624900818),
 ('well', 0.9986757040023804),
 ('morning', 0.9986433982849121),
 ('happy', 0.9986355900764465),
 ('not', 0.9986327886581421),
 ('oh', 0.9985097050666809),
 ('wa', 0.998508095741272),
 ('where', 0.9984791874885559),
 ('sleep', 0.9984655380249023)]

In [21]:
model.wv['good'].shape

(100,)

In [22]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [23]:
import numpy as np

def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)
    
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)
                #or [np.zeros(len(model.wv.index_to_key))], axis=0)

In [24]:
%pip install tqdm

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [25]:
from tqdm import tqdm

In [26]:
#apply for the entire sentences
import numpy as np
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

  7%|▋         | 384/5569 [00:00<00:01, 3836.47it/s]c:\PERSONAL\Conda\Lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\PERSONAL\Conda\Lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5569/5569 [00:01<00:00, 5163.37it/s]


In [27]:
X

[array([-0.18789561,  0.23113646,  0.11599318,  0.09154093,  0.09032387,
        -0.48645326,  0.17163737,  0.47157153, -0.24805115, -0.10911737,
        -0.1920312 , -0.37807423, -0.07913186,  0.11273914,  0.17056951,
        -0.15894756,  0.1336971 , -0.3112532 , -0.06432327, -0.5326796 ,
         0.19039233,  0.11076156,  0.07565984, -0.20302144, -0.02196056,
        -0.01852105, -0.19952634, -0.20358647, -0.2642446 ,  0.03362953,
         0.32635424,  0.02395993,  0.12296163, -0.18280663, -0.13872318,
         0.3731219 ,  0.07605828, -0.11325689, -0.09966107, -0.4773545 ,
         0.10146587, -0.24917811, -0.20028637,  0.0368671 ,  0.16146089,
         0.00569264, -0.12593801, -0.05938695,  0.22282569,  0.14053161,
         0.18060654, -0.19341841, -0.05234927,  0.06024243, -0.08286589,
         0.03973291,  0.17175989,  0.02167959, -0.3781548 ,  0.17509484,
        -0.01670193,  0.16196674, -0.00493718, -0.1373489 , -0.2750316 ,
         0.2618354 ,  0.09350058,  0.22704074, -0.3

In [28]:
len(X)

5569

In [29]:
##independent Features
# Only keep arrays with shape (100,)
X_new = np.vstack([arr for arr in X if arr.shape == (100,)])

In [30]:
messages.shape

(5572, 2)

In [31]:
X[1]

array([-1.71056628e-01,  2.02015713e-01,  9.89679545e-02,  7.76421279e-02,
        8.30175802e-02, -4.22178715e-01,  1.38663143e-01,  4.15608525e-01,
       -2.16202796e-01, -9.00428519e-02, -1.69211879e-01, -3.27287823e-01,
       -6.34008422e-02,  1.03107892e-01,  1.54801488e-01, -1.45574659e-01,
        1.14947215e-01, -2.74550468e-01, -6.08611926e-02, -4.68702108e-01,
        1.74785838e-01,  9.62060243e-02,  5.88223264e-02, -1.73722476e-01,
       -1.75923668e-02, -1.50631582e-02, -1.69418171e-01, -1.85723126e-01,
       -2.25878209e-01,  2.49531455e-02,  2.82177269e-01,  2.23357044e-02,
        1.02005392e-01, -1.63417682e-01, -1.21935025e-01,  3.23677808e-01,
        5.88395298e-02, -9.96277928e-02, -8.60343277e-02, -4.21484888e-01,
        8.42107087e-02, -2.09435314e-01, -1.66823342e-01,  2.44281739e-02,
        1.34551406e-01, -2.73755519e-03, -1.12219989e-01, -5.10662757e-02,
        1.99838698e-01,  1.24276161e-01,  1.51749462e-01, -1.59364074e-01,
       -4.32669818e-02,  

In [32]:
X_new.shape

(5557, 100)

In [33]:
X_new[0].shape

(100,)

In [34]:
## Dependent Features
## Output Features
y = messages[list(map(lambda x: len(x)>0 ,corpus))]
y=pd.get_dummies(y['label'])
y=y.iloc[:,0].values

In [35]:
y.shape

(5569,)

In [36]:
X[0].reshape(1,-1).shape

(1, 100)

In [ ]:
#This is the final independent features
df = pd.DataFrame([x.flatten() for x in X])

In [51]:
df.shape

(5569, 100)

In [48]:
df.head()

0         1         2         3         4         5         6   \
0 -0.187896  0.231136  0.115993  0.091541  0.090324 -0.486453  0.171637   
1 -0.171057  0.202016  0.098968  0.077642  0.083018 -0.422179  0.138663   
2 -0.200962  0.244317  0.124465  0.111488  0.073944 -0.519613  0.171219   
3 -0.255061  0.310861  0.150206  0.122446  0.122529 -0.657102  0.227722   
4 -0.219022  0.250841  0.133158  0.098516  0.113293 -0.553486  0.186451   

         7         8         9   ...        90        91        92        93  \
0  0.471572 -0.248051 -0.109117  ...  0.350791  0.155033  0.071306  0.057416   
1  0.415609 -0.216203 -0.090043  ...  0.312363  0.129269  0.057849  0.045706   
2  0.459954 -0.262863 -0.133349  ...  0.341205  0.154201  0.070282  0.044855   
3  0.646555 -0.338800 -0.140040  ...  0.477655  0.207054  0.093556  0.085003   
4  0.544630 -0.289676 -0.124059  ...  0.406182  0.172252  0.080885  0.074035   

         94        95        96        97        98        99  
0  0.439335  0.181933  0.178866 -0.191432  0.151259  0.009778  
1  0.373876  0.155511  0.158861 -0.174044  0.138441  0.000280  
2  0.443565  0.164276  0.126036 -0.221898  0.177526  0.028098  
3  0.585384  0.252072  0.261914 -0.259836  0.205859  0.002414  
4  0.493134  0.213186  0.211568 -0.228433  0.166916  0.002570  

[5 rows x 100 columns]

In [41]:
df['Output']=y

In [42]:
df.head()

Output
0    True
1    True
2   False
3    True
4    True

In [43]:
df.dropna(inplace=True)

In [44]:
df.isnull().sum()

Output    0
dtype: int64

In [52]:
## Independent Feature
X=df

In [53]:
X.isnull().sum()

0     12
1     12
2     12
3     12
4     12
      ..
95    12
96    12
97    12
98    12
99    12
Length: 100, dtype: int64

In [55]:
# The variable y is already defined and used. No need to redefine it from df.
y  # or simply leave this cell empty if you don't need to do anything here

array([ True,  True, False, ...,  True,  True,  True])

In [56]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [57]:
X_train.head()

0         1         2         3         4         5         6   \
1467 -0.054510  0.423788  0.159945  0.114908 -0.077976 -0.537666  0.355412   
1562 -0.159887  0.187642  0.093863  0.071369  0.072006 -0.396146  0.138052   
3120 -0.273732  0.291337  0.156930  0.106167  0.138946 -0.641180  0.217493   
3686 -0.192579  0.240488  0.121564  0.092123  0.092714 -0.501658  0.176213   
2453 -0.300839  0.301339  0.161427  0.111239  0.166955 -0.693727  0.221965   

            7         8         9   ...        90        91        92  \
1467  0.594422 -0.239361 -0.181589  ...  0.285242  0.235235  0.204774   
1562  0.386173 -0.204342 -0.089975  ...  0.290499  0.133055  0.058877   
3120  0.639215 -0.337258 -0.149800  ...  0.499374  0.206340  0.099970   
3686  0.488840 -0.260233 -0.116176  ...  0.367451  0.161028  0.074329   
2453  0.698408 -0.355024 -0.142603  ...  0.533769  0.211284  0.089122   

            93        94        95        96        97        98        99  
1467  0.149790  0.576449  0.204477  0.298381 -0.034197  0.154437 -0.085020  
1562  0.050534  0.364072  0.153774  0.151130 -0.159206  0.123426  0.004948  
3120  0.092352  0.576070  0.282894  0.264852 -0.261456  0.176630  0.010678  
3686  0.060619  0.446300  0.186800  0.182505 -0.198664  0.154961  0.010942  
2453  0.100073  0.616813  0.304437  0.295431 -0.292066  0.190029  0.010891  

[5 rows x 100 columns]

In [58]:
y_train

array([ True,  True,  True, ...,  True,  True,  True])

In [59]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [60]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [61]:
y_pred=classifier.predict(X_test)

In [62]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))

0.9712746858168761


In [63]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.87      0.89      0.88       130
        True       0.99      0.98      0.98       984

    accuracy                           0.97      1114
   macro avg       0.93      0.94      0.93      1114
weighted avg       0.97      0.97      0.97      1114

